// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpVHAiSc-UqvQqtsLOb3vqEigUsgQdXhc',
    appId: '1:74337324883:web:d3e97dc47d08c2f4689ba6',
    messagingSenderId: '74337324883',
    projectId: 'car-service-app-a3cb2',
    authDomain: 'car-service-app-a3cb2.firebaseapp.com',
    databaseURL: 'https://car-service-app-a3cb2-default-rtdb.firebaseio.com',
    storageBucket: 'car-service-app-a3cb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb5XBDca1HFbSXKmcrwNoXku6Fdvz8474',
    appId: '1:74337324883:android:e6ca77742c356b1b689ba6',
    messagingSenderId: '74337324883',
    projectId: 'car-service-app-a3cb2',
    databaseURL: 'https://car-service-app-a3cb2-default-rtdb.firebaseio.com',
    storageBucket: 'car-service-app-a3cb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6DrMrOPAr1cefX-cuZyYf9XAMih1F0s',
    appId: '1:74337324883:ios:e367f65f533c29fc689ba6',
    messagingSenderId: '74337324883',
    projectId: 'car-service-app-a3cb2',
    databaseURL: 'https://car-service-app-a3cb2-default-rtdb.firebaseio.com',
    storageBucket: 'car-service-app-a3cb2.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6DrMrOPAr1cefX-cuZyYf9XAMih1F0s',
    appId: '1:74337324883:ios:01e9e11873782975689ba6',
    messagingSenderId: '74337324883',
    projectId: 'car-service-app-a3cb2',
    databaseURL: 'https://car-service-app-a3cb2-default-rtdb.firebaseio.com',
    storageBucket: 'car-service-app-a3cb2.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
